### ISSUE TITLE
Resolutions shifting

### ISSUE THREAD

**Issue by harleygodzisz** [SvenVD/rpisurv#107]
Having accidently bricking my old setup, I've now rebuilt it but the RTSP streams are shifted over by approximately 40 pixels and the 2x2 display is showing a large dead area at the bottom side.
I have tried to force stretch and to set sizes and even force locations. but doesn't seem to be working.

My streams are 360x240 and my screen resolution s 720x480.

**Comment by SvenVD** [comment]
Support questions should be asked on https://community.rpisurv.net/

Have you already tried the suggestion 
'`On a raspberry pi 3 and 4 it seems the default overscan settings are not good. If full screen is not used, if you have an unused bar in the bottom -> try to set disable_overscan=1 in /boot/config.txt' `
as stated on https://github.com/SvenVD/rpisurv/blob/master/README.md ?
