### ISSUE TITLE
Warn if gpu_mem is too low?

### ISSUE THREAD

**Issue by puck** [SvenVD/rpisurv#11]
I found I wasn't able to start more than 2 streams with the default gpu_mem setting. Perhaps having some logic that warns with a suitable warning if you fail to spawn additional streams?  I only thought this might be an issue after looking at the README file.

**Comment by SvenVD** [comment]
Normally there should be some  kind of error logged. Did you see something in the logs?

**Comment by SvenVD** [comment]
I added a warning in the logs when free gpu mem is too low : https://github.com/SvenVD/rpisurv/commit/3d3461c580aaab93c03b071e448d33f2d42edad3

Please check it out

**Comment by puck** [comment]
I set gpu_mem back to default, and I can confirm that the logging works beautifully and I now know exactly what is wrong!

Thank you.
