### ISSUE TITLE
without HMDI connection? ony framebuffer?

### ISSUE THREAD

**Issue by ozett** [SvenVD/rpisurv#111]
hi, 
sorry if doubled to tapatalk, but i am not experienced there and dont know if it is seen.

rpisurf is running fine with a display connected on hdmi.
but now i will only use my frambuffer-tft and pygame? throws an error that there is no hardware.

how to force rpisurf to frambuffer?
in the gerneral.yml there is a fallback? how to force this?

```
root@raspberrypi:/usr/src/rpisurv# rpisurv start
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
2021/01/05 15:10:41 - l_default - INFO - Starting rpisurv 3.0.0-beta4
[E] No device present
Traceback (most recent call last):
  File "surveillance.py", line 159, in <module>
    displays=parse_tvservice()
  File "surveillance.py", line 88, in parse_tvservice
    autodetected_display["device_name"] = regex_result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Does this help somehow?
https://learn.adafruit.com/pi-video-output-using-pygame/pointing-pygame-to-the-framebuffer

thx

**Comment by SvenVD** [comment]
I will close this ticket since this is a duplicate, let's continue in https://www.tapatalk.com/groups/rpisurv/rpisurf-only-on-framebuffer-t90.html
