### ISSUE TITLE
[RFE] v3 default install setup to be valid

### ISSUE THREAD

**Issue by DumpySquare** [SvenVD/rpisurv#114]
As a new user, just getting started with this kind of technology and this project specifically, it would be nice to have  the install script setup that would finish with a working solution with demo graphics.  Then the user could work through getting streams setup.  This would remove product errors from user errors during the initial stages.

**Comment by SvenVD** [comment]
version 3 does exactly that: https://github.com/SvenVD/rpisurv/tree/v3_latest
