### ISSUE TITLE
RTMP 

### ISSUE THREAD

**Issue by Minglarn** [SvenVD/rpisurv#119]
Hi! 
Trying to get FRIGATEs RTMP streams to work with RPISURV with no luck. 

Running you 3.0.7beta and get these in the logs: 
`ERROR - CameraStream: screen_manager_1_screen1_cam_stream1 rtmp://192.168.1.121/live/frigate_entren Not Connectable (ffprobe timed out, try increasing probe_timeout for this stream), configured timeout: 3`

It works well with VLC but not with rpisurv. 
Any hints?

http stream works but it puts some heavy load on my NUC so it's not an option.

**Comment by akoryuerek** [comment]
Try to increase probe_timeout and it will work.

**Comment by Minglarn** [comment]
It worked! Thanks... Must have missed that option... :)
probe_timeout is set to 20 and it works...
