### ISSUE TITLE
Feature: Cycle through streams

### ISSUE THREAD

**Issue by puck** [SvenVD/rpisurv#12]
I have more than 4 cameras I'd like to display, but I'm happy to have them cycle. Any thoughts on adding support for cycling through streams?

**Comment by SvenVD** [comment]
Currently no plans. This needs another core mechanism of adjusting existing streams, which theoretically can be done with dbus, redrawing the screen is currently to slow to have a smooth rotation.

**Comment by SvenVD** [comment]
Hi, this is now possible with the beta 2.0

**Comment by puck** [comment]
Fantastic! Thank you for the update.
