### ISSUE TITLE
Streams occasionally reconnect

### ISSUE THREAD

**Issue by MisterMelDev** [SvenVD/rpisurv#120]
Thank you for creating this project, it works really well.

The only issue I'm experiencing is that the streams sometimes cut out, then come back after a few seconds. It seems to me that rpisurv is just reconnecting, but why does it do this? It's not really a big deal but maybe it could instead reconnect in the background and only display the new connection once it has finished connecting? I'm running the latest v3 version.

**Comment by SvenVD** [comment]
You have to provide the logs to know what is happening, why Rpisurv is reconnecting

https://www.tapatalk.com/groups/rpisurv/guidelines-t119.html
