### ISSUE TITLE
Help a noob :)

### ISSUE THREAD

**Issue by MrPresident2** [SvenVD/rpisurv#121]
Hey guys, I've been looking for a way to watch RTSP and HTTP streams and it seems like this is the only way and from what I see on other people it seems like it's working great. but I can make it work with my raspberry pi 4.
after going through the install guide when I reboot the pi I'm getting nothing just a black screen with what looks like hss screen but no stream, can anyone help me with that? maybe go with me on the installation process? I'm so lost ill even pay for someone's time to help me out.
Thanks

**Comment by SvenVD** [comment]
Please provide output of

-  /usr/local/bin/rpisurv/logs/main.log
- /var/log/daemon.log
- you config file


so we can figure out what is wrong

remove password first

**Comment by MrPresident2** [comment]
> * /usr/local/bin/rpisurv/logs/main.log

Thank you for your help,
I'm kind of a noob at all of this, how can I find those files? when I look at the sd card on my pc I don't see any of those files or directories.

**Comment by MrPresident2** [comment]
no answer so ill close the post
