### ISSUE TITLE
Invalid framerate 90000

### ISSUE THREAD

**Issue by cashxx** [SvenVD/rpisurv#13]
Just got things setup and manually starting rpisurv with cd /usr/local/bin/rpisurv; python surveillance.py and it comes up with - Invalid framerate 90000, using forced 25fps and just trust timestamps have a nice day ;) and just keeps trying to connect to the stream.   The stream works in VLC and QT.   Says its connectable.  Not sure what the issue is? Logs basically repeat the same.

**Comment by cashxx** [comment]
Me being stupid....Run GUI

**Comment by burt-macklin1** [comment]
@cashxx  I am having the same issue, if you remember could you elaborate on your fix?
