### ISSUE TITLE
Maintaining the aspect ratio of the video feeds

### ISSUE THREAD

**Issue by UntouchedWagons** [SvenVD/rpisurv#137]
I have a Pi 3 with the 7" touchscreen, it has a resolution of 800x480. I want to have two video feeds with aspect ratios of 4:3 displayed side but rpisurv stretches the video feeds to take up the full 480 pixels of height. How do I tell rpisurv to prioritize maintaining the aspect ratio of the feeds?

This is my display1.yml:

    essentials:
      screens:
        - camera_streams:
            - url: "rtmp://homeassistant.untouchedwagons.site:1935/live/front_door"
              probe_timeout: 20
            - url: "rtmp://homeassistant.untouchedwagons.site:1935/live/side_door"
              probe_timeout: 20
          nr_of_columns: 2

Would I have to use the force_coordinates directives?

**Comment by SvenVD** [comment]
> Would I have to use the force_coordinates directives?

Yes

**Comment by UntouchedWagons** [comment]
Okay
