### ISSUE TITLE
error in config file Rpisurv v3

### ISSUE THREAD

**Issue by daendaen** [SvenVD/rpisurv#138]
Hi, I'm just trying to get one camera stream running first.
I have Kamersa from Unifi. The RTSP link is correct (test in VLC player is positive)
The stream is not displayed, the connection (purple font) is the only thing I see

After the installation, the demo runs partially (2 of 4 streams are displayed. I have inserted my stream link, but as I said nothing comes up

If I enter a photo as a source (url), it will be loaded without any problems

Does somebody has any idea?

daemon.log

Oct 17 20:50:29 raspberrypi systemd[1]: Started Rpisurv Raspberry Pi Surveillance.
Oct 17 20:50:31 raspberrypi rpisurv[1048]: pygame 1.9.4.post1
Oct 17 20:50:31 raspberrypi rpisurv[1048]: Hello from the pygame community. https://www.pygame.org/contribute.html
Oct 17 20:50:31 raspberrypi rpisurv[1048]: 2021/10/17 20:50:31 - l_default - INFO - Starting rpisurv 3.0.0-beta7
Oct 17 20:50:31 raspberrypi rpisurv[1048]: 2021/10/17 20:50:31 - l_default - DEBUG - Make sure vlc binary can be executed as root
Oct 17 20:50:31 raspberrypi rpisurv[1048]: 2021/10/17 20:50:31 - l_default - INFO - Auto detected display GSM-LG_ULTRAWIDE at HDMI 0 with display number 2 1920 x 1080
Oct 17 20:50:31 raspberrypi rpisurv[1048]: 2021/10/17 20:50:31 - l_default - INFO - Unique id of this installation is 1a7ffc14ad4341afeeb729901f965188bfdb754d94a4bef53a978c6ab35332e8
Oct 17 20:50:31 raspberrypi rpisurv[1048]: 2021/10/17 20:50:31 - l_default - DEBUG - Start_time is 1634496631.1819744
Oct 17 20:50:35 raspberrypi rpisurv[1048]: 2021/10/17 20:50:35 - l_default - DEBUG - screen_manager_0: Looking for config file conf/display1.yml
Oct 17 20:50:35 raspberrypi rpisurv[1048]: Traceback (most recent call last):
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "surveillance.py", line 188, in <module>
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     screen_manager=ScreenManager(f'screen_manager_{count}', display, enable_opportunistic_caching_next_screen, disable_pygame)
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 21, in __init__
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     self._fetch_display_config()
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 40, in _fetch_display_config
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     cfg = yaml.load(ymlfile)
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     return loader.get_single_data()
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     node = self.get_single_node()
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     document = self.compose_document()
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     node = self.compose_node(None, None)
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     node = self.compose_mapping_node(anchor)
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     while not self.check_event(MappingEndEvent):
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     self.current_event = self.state()
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
Oct 17 20:50:35 raspberrypi rpisurv[1048]:     "expected <block end>, but found %r" % token.id, token.start_mark)
Oct 17 20:50:35 raspberrypi rpisurv[1048]: yaml.parser.ParserError: while parsing a block mapping
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   in "conf/display1.yml", line 4, column 1
Oct 17 20:50:35 raspberrypi rpisurv[1048]: expected <block end>, but found '-'
Oct 17 20:50:35 raspberrypi rpisurv[1048]:   in "conf/display1.yml", line 18, column 1
Oct 17 20:50:35 raspberrypi systemd[1]: rpisurv.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 20:50:35 raspberrypi systemd[1]: rpisurv.service: Failed with result 'exit-code'.

**Comment by SvenVD** [comment]
Hi Rpisurv does not even start because it can not parse the display1.yml config file


```
Oct 17 20:50:35 raspberrypi rpisurv[1048]: yaml.parser.ParserError: while parsing a block mapping
Oct 17 20:50:35 raspberrypi rpisurv[1048]: in "conf/display1.yml", line 4, column 1
Oct 17 20:50:35 raspberrypi rpisurv[1048]: expected , but found '-'
Oct 17 20:50:35 raspberrypi rpisurv[1048]: in "conf/display1.yml", line 18, column 1
```

You made a mistake in the config file on those lines.
