### ISSUE TITLE
All streams are flashing/flickering

### ISSUE THREAD

**Issue by daendaen** [SvenVD/rpisurv#139]
Hi,

i installed a fresh installation of rpisurv on a raspberry 4 (4GB). 
2 streams are not a problem. If I use more than two streams this flashes / flickers appear, see the youtube link

https://www.youtube.com/watch?v=pTbfSWBGbeo

Anyone have an idea?

Greetings

**Comment by SvenVD** [comment]
Try using lower resolution streams.
