### ISSUE TITLE
Failing for VLC

### ISSUE THREAD

**Issue by sjobbe** [SvenVD/rpisurv#140]
Your version of vlc does not have the needed mmal options. Rpisurv needs those
Minimum tested vlc version for Rpisurv is (VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
Aborting installation, upgrade to latest vlc player with mmal support

root@vmt-rpi2-mh02:/home/sjobbe/rpisurv-3_latest# vlc --version
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
VLC version 3.0.16 Vetinari (3.0.13-8-g41878ff4f2)

**Comment by SvenVD** [comment]
no response close

**Comment by gabiX87** [comment]
Same here , fresh install from NOOBs , RPI OS Lite 
**pi@raspberrypi:/tmp/rpisurv $**  cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**pi@raspberrypi:/tmp/rpisurv $**  vlc --version
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
VLC version 3.0.16 Vetinari (3.0.13-8-g41878ff4f2)
Compiled by serge on arm-build.pitowers.org (Nov 10 2021 15:40:45)
Compiler: gcc version 10.2.1 20210110 (Debian 10.2.1-6)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public Licence;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.


(installing rpisurv) .......
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
**Your version of vlc does not have the needed mmal options. Rpisurv needs those
Minimum tested vlc version for Rpisurv is (VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
Aborting installation, upgrade to latest vlc player with mmal support**

**pi@raspberrypi:/tmp/rpisurv $** sudo apt-get install vlc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**vlc is already the newest version (3.0.16-1+rpi1+rpt2).**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by gabiX87** [comment]
meh , go there  https://github.com/SvenVD/rpisurv/issues/143
