### ISSUE TITLE
Shutdown still feeding camera streams?

### ISSUE THREAD

**Issue by chrismaaz** [SvenVD/rpisurv#148]
Even when rpisurv is not running, I am seeing an uplink of around 50-60 mbps feeding to my Pi from my Wifi access point. I have a fresh install of Buster and nothing else running on it. 

`sudo systemctl stop rpisurv`

I have no idea what's going on, any ideas?

**Comment by SvenVD** [comment]
Try with one of the network monitoring tools https://raspberrypi.stackexchange.com/questions/8162/network-monitor-by-process  to see if something is still using bandwidth
