### ISSUE TITLE
fuzzy images on 3 of 4 cams

### ISSUE THREAD

**Issue by skueppers** [SvenVD/rpisurv#16]
First of all thanks for your great script which runs (nearly) charming after a few pitfalls.
My current problem is that 3 of my 4 cams only show a "fuzzy" picture - as well as if streaming "by default" oder "over tcp".
![rpisurv](https://cloud.githubusercontent.com/assets/12424923/18094168/cd4eb4ce-6ed2-11e6-8b47-bec093a1bd1f.jpg)
All in all my RasPi uses currently 50-60% CPU

Although this is not a specific problem with rpisurv maybe you have the crucial hint

**Comment by SvenVD** [comment]
Did you assign enough memory to the GPU?

**Comment by skueppers** [comment]
currently running with gpu_mem=384 "only"
setting gpu_mem to 512 makes the system ghastly slow

**Comment by SvenVD** [comment]
What version of omxplayer are you using?
