### ISSUE TITLE
No  stream shown

### ISSUE THREAD

**Issue by winkelu** [SvenVD/rpisurv#169]
Hello 
I get the following error

pygame, used to display image, is not compatible with dispmanx layers caching mechanism

installed version 3 
on buster lite 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

/usr/include/python3.7m/pygame
/usr/lib/python3/dist-packages/pygame

Demo is ok

any thoughts?
thanks in advance

**Comment by SvenVD** [comment]
more info is needed, as in what is the problem you are experiencing. The error by itself should not stop rpisurv. Are you using image streams? Multiple HDMI?

**Comment by winkelu** [comment]
Even with only the Demo I get this error but demo is working
I have  only one Monitor attached
Same with buster full

**Comment by SvenVD** [comment]
What is the problem you are experiencing?
