### ISSUE TITLE
pisurv not starting 

### ISSUE THREAD

**Issue by staticgroup** [SvenVD/rpisurv#175]
Hey Sven,

Unfortuantely pisurv stopped starting on one of my pi's I moved it and plugged into hdmi 1 not 0 but soon corrected .

Jul 05 09:54:12 shedrstppii rpisurv[932]: Hello from the pygame community. https://www.pygame.org/contribute.html
Jul 05 09:54:12 shedrstppii rpisurv[932]: 2023/07/05 09:54:12 - l_default - INFO - Starting rpisurv 3.0.0
Jul 05 09:54:12 shedrstppii rpisurv[932]: [E] No device present
Jul 05 09:54:12 shedrstppii rpisurv[932]: 2023/07/05 09:54:12 - l_default - ERROR - Could not retrieve devicename for display 2
Jul 05 09:54:12 shedrstppii rpisurv[932]: 2023/07/05 09:54:12 - l_default - ERROR - Could not autodetect displays, use values from fallback config
Jul 05 09:54:12 shedrstppii rpisurv[932]: 2023/07/05 09:54:12 - l_default - ERROR - Using config display fallback_device_0 at HDMI 0 with display number 2 1920 x 1080

**Comment by SvenVD** [comment]
you still have the problem?
