### ISSUE TITLE
Camera can be reached via ping and via VLC on a desktop but stuck on connecting

### ISSUE THREAD

**Issue by C1137** [SvenVD/rpisurv#177]
Whenever I attempt to use RSTP to connect to my camera, I get stuck at the connecting screen, but given that it recognizes as a camera and at least tries to connect makes me think I'm on the right track. When checking the logs, the only relevant message I get is 

'screen_manager_0: skip caching next screen: screen_manager_0_screen2 (pygame, used to display image, is not compatible with dispmanx layers caching mechanism)'

This is using a Pi 3B and a Mobotix Mx-VD1A-8-IR-VA dome camera.

**Comment by SvenVD** [comment]
what is your config

**Comment by SvenVD** [comment]
stale issue
