### ISSUE TITLE
can it do multi page screens

### ISSUE THREAD

**Issue by xbipin** [SvenVD/rpisurv#18]
basically i have a DVR with 16 cams and i want to show 9 cams first then after a timeout period show the next 7 and keep rotating this,i believe this is not possible

**Comment by SvenVD** [comment]
Sorry, It can not currently do this

**Comment by xbipin** [comment]
is there any possibility to add this feature as i think it should be very useful when u have a lot of cameras

**Comment by SvenVD** [comment]
Hi currently no plans in that direction. But I am open to a pull requests.
