### ISSUE TITLE
2 streams 1 column fails to work

### ISSUE THREAD

**Issue by itsmeduhdoi** [SvenVD/rpisurv#184]
I'm trying to have 2 camera streams appear on screen in 1 column, but when they both load, and i have to force tcp to get them to, they don't refresh.  They don't get detected as dead streams, and i can log in to the cameras themselves and see that they are sending a stream to my rpisurv device, but the streams the device shows are a static image of when it first connected.

1 single stream, of either camera, works as expected.

occasionally, using backspace to return to command line, making adjustments in the display1.yml and restarting causes the device to lockup and i have to manually power cycle to get it functioning again.

**Comment by SvenVD** [comment]
try lower resolution substreams

**Comment by itsmeduhdoi** [comment]
Ok,
Will do.  I have these cameras set with their main stream at h.265, but the sub stream at h.264
some googling has informed me that these cameras don't correctly pass their substreams over rtsp...all url's connect only to the main stream.

**Comment by itsmeduhdoi** [comment]
> try lower resolution substreams

got ahold of the manufacturer support group, the URL for these cameras to get to the substream had to be ip:port/multicast/video2  any other version of a url would work but only pull the main stream.

1 column will work now, did i just miss that this can't handle high quality camera feeds somewhere?  thank you

**Comment by SvenVD** [comment]
it depends on the hardware of the raspberry pi, it has a limit on how much downscalen from a highr resolution to fit within the window you want to show your stream. Generally try to avoid downscaling.
