### ISSUE TITLE
nr_of_columns: 3 not working

### ISSUE THREAD

**Issue by abhi237086** [SvenVD/rpisurv#186]
when i set the number of columns  to 3 then  rpisurv is not loading, Just working on columns i.e Default 2
in Log I ma getting  l_default - ERROR - Skipping calculating free malloc memory because of TimeoutExpired(['/usr/bin/vcgencmd', 'get_mem', 'malloc'], 1)

screens:
    - camera_streams:
        - url: "rtmp://192.168.1.188/live/test1"
        - url: "rtmp://192.168.1.188/live/test2"
        - url: "rtmp://192.168.1.188/live/test3"
        - url: "rtmp://192.168.1.188/live/test4"
        - url: "rtmp://192.168.1.188/live/test5"
        - url: "rtmp://192.168.1.188/live/test6"
        - url: "rtmp://192.168.1.188/live/test7"
        - url: "rtmp://192.168.1.188/live/test8"
        - url: "rtmp://192.168.1.188/live/test9"
    nr_of_columns: 3
     duration: 20
     
     
     Model           : Raspberry Pi 4 Model B Rev 1.2
     OS : Buster

**Comment by abhi237086** [comment]
If i Upgrade it to 8 GB then it will work for 9 Stream.

**Comment by akoryuerek** [comment]
Unlikely, you need more cpu and/or gpu power. Ram doesn't decode streams.

**Comment by SvenVD** [comment]
FYI, https://opensurv.net with the correct hardware can enable you 20 streams or even more. Closing this issue for now
