### ISSUE TITLE
E: Package 'vlc' has no installation candidate

### ISSUE THREAD

**Issue by wifispray** [SvenVD/rpisurv#188]
Getting this error on install.

pi@raspberrypi:~/rpisurv $ sudo ./install.sh
Use this installer on your own risk. Make sure this host does not contain important data and is replacable
This installer will disable graphical login on your pi, please revert with the raspi-config command if needed.

The following version will be installed: "3.0.0"

Do you want to continue press <Enter>, <Ctrl-C> to cancel

Hit:1 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package vlc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'vlc' has no installation candidate
sed: can't read /usr/bin/vlc: No such file or directory
Your version of vlc does not have the needed mmal options. Rpisurv needs those
Minimum tested vlc version for Rpisurv is (VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72),
Maximum tested vlc version for Rpisurv is (VLC media player 3.0.17.4 Vetinari (3.0.13-8-g41878ff4f2)
Aborting installation, upgrade to latest vlc player with mmal support

**Comment by SemoTech** [comment]
@wifispray I am having the same VLC issue [here](https://github.com/SvenVD/rpisurv/issues/189).  Seems VLC "mmal" and bookworm are not liking each-other. I tried both 32Bit and 64Bit bookworm on a Pi5 with same effect.

**Comment by SvenVD** [comment]
Seems we are also bumping into https://github.com/RPi-Distro/vlc/issues/80#issuecomment-1817884925. As I understand drm replaces mmal, but lacks the windows coordinates functionality for multiple instances

**Comment by SvenVD** [comment]
follow up here  https://github.com/SvenVD/rpisurv/issues/189
