### ISSUE TITLE
Custom images

### ISSUE THREAD

**Issue by Adsyadsman** [SvenVD/rpisurv#36]
Hi,
Firstly, a big thanks for such an awesome app. Ive just started benchtesting and so far so good.
Just wanted to know about the custom images to replace the stock 'connecting', 'no connection' and 'placeholder' images.
Are there any image or file size constraints for these to work?
I tried some basic 1920x1080 pngs in the /images folder, but after a restart the rpi still shows the stock images.

Secondly, would there be any possibility to add a custom watermark or overlay a static image in a corner of the screen?

Any help would be appreciated.

Thanks.

**Comment by SvenVD** [comment]
Hi, probably the README is not clear on this. I will update this, but you need to either replace the images in the images folder en then run install.sh again OR you can replace the images in their final destination "/usr/local/bin/rpisurv/images/"

Currently no direct plans to add an overlay, but I will keep this in mind.

**Comment by SvenVD** [comment]
If omxplayer is avaiIable and all needed python libraries this could work. But I do not own such a board, so I have not tested it.
