### ISSUE TITLE
rpi 3 using wifi starting rpisurv before actually connected to wifi

### ISSUE THREAD

**Issue by si458** [SvenVD/rpisurv#43]
when using the latest raspbian on RPI 3 AND using WiFi,

it appears the rpisurv is starting before the pi has actually connected to the network by wifi

i have used raspi-config to say WAIT UNTIL NETWORK CONNECTED

but its having no affect?

**Comment by SvenVD** [comment]
Do you still have the wired connection plugged in? Rpisurv start the moment there at least one network device which is up

**Comment by si458** [comment]
its wireless only, no lan cable plugged in :(

**Comment by SvenVD** [comment]
Can you try:

systemctl enable systemd-networkd-wait-online.service

**Comment by si458** [comment]
Sorry for delay

pi@raspberrypi:~ $ systemctl enable systemd-networkd-wait-online.service 
Failed to enable unit: The name org.freedesktop.PolicyKit1 was not provided by any .service files
pi@raspberrypi:~ $

**Comment by si458** [comment]
Sorry ignore that forgot to use sudo

That enabled the service  but after reboot it still loads before the network and says all streams are not available

**Comment by si458** [comment]
Pi@raspberrypi:~ $ sudo systemctl enable systemd-networkd-wait-online.service 
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /lib/systemd/system/systemd-networkd-wait-online.service.
pi@raspberrypi:~ $

**Comment by Jmtyra** [comment]
I had a similar issue with rpisurv loading before the network was ready, wired only in my situation. Enabling systemd-networkd-wait-online.service did not resolve the issue.

Editing the /usr/bin/rpisurv file and adding /bin/sleep 10 resolved the issue in my case. This provided enough of a delay for the network to be active. Resulting rpisurv file:

![2017-12-19 20_06_33-sighthound-dmz - vmware remote console](https://user-images.githubusercontent.com/7514676/34187667-2b737692-e4f8-11e7-974d-61f363cbfa59.jpg)

**Comment by SvenVD** [comment]
I can not reproduce the issue. Could you try to

Wants=network-online.target

to the systemd file and reboot

` cat /etc/systemd/system/rpisurv.service
[Unit]
Description=Rpisurv Raspberry Pi Surveillance
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/rpisurv
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
`

**Comment by Jmtyra** [comment]
My current systemd file already has these lines in place.

**Comment by SvenVD** [comment]
I run rpisurv (rpi 2) on dhcp but wired. I do not see any issues with dhcp configured.

**Comment by Jmtyra** [comment]
Might be something unique with my setup. Thank you for looking into this issue. :)
