### ISSUE TITLE
Delays in display

### ISSUE THREAD

**Issue by skowron0** [SvenVD/rpisurv#44]
Hi,

I usage five china camera 2Mpx. In day mode all works wery well.
After change to night mode within an hour the image is delayed by a few minutes.
Do you have a solution?
I use substream 640x480px 15fps.

Wersion of my cameras:
![camera_version](https://user-images.githubusercontent.com/7578684/32557689-248aea10-c4a3-11e7-8189-05047b28a0ba.png)

best regards
Krzysztof

**Comment by SvenVD** [comment]
This is probably an issue with your cameras? Switching to nightvision should make no difference for rpisurv.

**Comment by skowron0** [comment]
The problem is strange because when I use this stream link on vlc or ONVIF Device Manager this problem does not exist. This is only visible when I use omxplayer.

**Comment by SvenVD** [comment]
I am just guessing since I can't help you with specific camera issues. But maybe the delay just builds up over time? Try running the stream with vlc for a longer time and see if delay cumulates. 

What happens if you restart rpisurv? Is the delay gone? You could schedule a workaround to restart rpisurv every hour or so.

**Comment by skowron0** [comment]
Yes, the delay just builds up over time - only when use omxplayer. When I use vlc there are no delays even after a few hours.
When I restart rpisurv delay is gone.
Within 30 minutes the delay can be up to 8 minutes.
When I disconnect the camera from the network, the video is displayed as if delayed, as if the omxplayer had accumulated the stream.

**Comment by SvenVD** [comment]
You should ask the omxplayer guys.

Maybe you can try setting  --video_fifo 1 --video_queue 1 in worker.py als one of the arguments of omxplayer

**Comment by skowron0** [comment]
All the time I have this problem, unfortunately your suggest did not work.
When I have statistics turned on, the parameter marked in red is less than 1 second. In night mode this parameter is constantly increasing. Could this be causing the instability of fps?
I see that you have a lot of experience with omxplayer and maybe you can suggest something else.
I also described the problem on the omxplayer page but no one writes ...
![omxplayer](https://user-images.githubusercontent.com/7578684/33303511-d143a3c2-d403-11e7-9da8-650eb7b9d0b5.png)

**Comment by afburgos** [comment]
This happens to me as well, the cameras are 15 fps and happens by day and
by night.  The only solution I found is reestart the pi everyday.

El 28 nov. 2017 6:19 a. m., "skowron0" <notifications@github.com> escribió:

All the time I have this problem, unfortunately your suggest did not work.
When I have statistics turned on, the parameter marked in red is less than
1 second. In night mode this parameter is constantly increasing. Could this
be causing the instability of fps?
I see that you have a lot of experience with omxplayer and maybe you can
suggest something else.
I also described the problem on the omxplayer page but no one writes ...
[image: omxplayer]
<https://user-images.githubusercontent.com/7578684/33303511-d143a3c2-d403-11e7-9da8-650eb7b9d0b5.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SvenVD/rpisurv/issues/44#issuecomment-347416641>, or mute
the thread

**Comment by SvenVD** [comment]
Are these wireless cameras?

**Comment by afburgos** [comment]
Not mine. All them are wired.



2017-11-29 22:28 GMT+01:00 SvenVD <notifications@github.com>:

**Comment by skowron0** [comment]
I also have everything connected by cable.

**Comment by skowron0** [comment]
I found problem with gpu_mem in my log.
In config.txt i setted gpu_mem_1024=548.
Sometimes the value of gpu memory drops to zero, then returns several hundred MB.

my log:

2017/12/04 08:27:21 - l_default - DEBUG - stats_counter is 21. Only sending every 40
2017/12/04 08:27:21 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:27:21 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:27:21 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:27:21 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:27:21 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:27:21 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:27:21 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:27:46 - l_default - DEBUG - stats_counter is 22. Only sending every 40
2017/12/04 08:27:46 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:27:46 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:27:46 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:27:46 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:27:46 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:27:47 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:27:47 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:28:12 - l_default - DEBUG - stats_counter is 23. Only sending every 40
2017/12/04 08:28:12 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:28:12 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:28:12 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:28:12 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:28:12 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:28:12 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:28:12 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:28:37 - l_default - DEBUG - stats_counter is 24. Only sending every 40
2017/12/04 08:28:37 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:28:37 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:28:37 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:28:37 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:28:37 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:28:37 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:28:37 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:29:02 - l_default - DEBUG - stats_counter is 25. Only sending every 40
2017/12/04 08:29:02 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:29:02 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:29:02 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:29:02 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:29:02 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:29:02 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:29:02 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:29:27 - l_default - DEBUG - stats_counter is 26. Only sending every 40
2017/12/04 08:29:27 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:29:27 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:29:27 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:29:27 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:29:27 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:29:27 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:29:27 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:29:52 - l_default - DEBUG - stats_counter is 27. Only sending every 40
2017/12/04 08:29:52 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:29:52 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:29:52 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:29:53 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:29:53 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:29:53 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:29:53 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:30:18 - l_default - DEBUG - stats_counter is 28. Only sending every 40
2017/12/04 08:30:18 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:30:18 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:30:18 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:30:18 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:30:18 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:30:18 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:30:18 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:30:43 - l_default - DEBUG - stats_counter is 29. Only sending every 40
2017/12/04 08:30:43 - l_default - DEBUG - Free gpu memory value is 0
2017/12/04 08:30:43 - l_default - DEBUG - Free memory in bytes: 0.0
2017/12/04 08:30:43 - l_default - ERROR - Free gpu mem is 0.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/04 08:30:43 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:30:43 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:30:43 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:30:43 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:30:43 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:31:08 - l_default - DEBUG - stats_counter is 30. Only sending every 40
2017/12/04 08:31:08 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:31:08 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:31:08 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:31:08 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:31:08 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:31:08 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:31:08 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:31:33 - l_default - DEBUG - stats_counter is 31. Only sending every 40
2017/12/04 08:31:33 - l_default - DEBUG - Free gpu memory value is 384
2017/12/04 08:31:33 - l_default - DEBUG - Free memory in bytes: 384.0
2017/12/04 08:31:33 - l_default - ERROR - Free gpu mem is 384.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/04 08:31:33 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:31:33 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:31:33 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:31:33 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:31:33 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:31:58 - l_default - DEBUG - stats_counter is 32. Only sending every 40
2017/12/04 08:31:59 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:31:59 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:31:59 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:31:59 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:31:59 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:31:59 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:31:59 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:32:24 - l_default - DEBUG - stats_counter is 33. Only sending every 40
2017/12/04 08:32:24 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:32:24 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:32:24 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:32:24 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:32:24 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:32:24 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:32:24 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:32:49 - l_default - DEBUG - stats_counter is 34. Only sending every 40
2017/12/04 08:32:49 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:32:49 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:32:49 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:32:49 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:32:49 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:32:49 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:32:49 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:33:14 - l_default - DEBUG - stats_counter is 35. Only sending every 40
2017/12/04 08:33:14 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:33:14 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:33:14 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:33:14 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:33:14 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:33:14 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:33:14 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:33:39 - l_default - DEBUG - stats_counter is 36. Only sending every 40
2017/12/04 08:33:39 - l_default - DEBUG - Free gpu memory value is 1K
2017/12/04 08:33:39 - l_default - DEBUG - Free memory in bytes: 1024.0
2017/12/04 08:33:39 - l_default - ERROR - Free gpu mem is 1024.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/04 08:33:39 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:33:39 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:33:39 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:33:39 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:33:39 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:34:04 - l_default - DEBUG - stats_counter is 37. Only sending every 40
2017/12/04 08:34:05 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:34:05 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:34:05 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:34:05 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:34:05 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:34:05 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:34:05 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:34:30 - l_default - DEBUG - stats_counter is 38. Only sending every 40
2017/12/04 08:34:30 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:34:30 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:34:30 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:34:30 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:34:30 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:34:30 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:34:30 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:34:55 - l_default - DEBUG - stats_counter is 39. Only sending every 40
2017/12/04 08:34:55 - l_default - DEBUG - Free gpu memory value is 0K
2017/12/04 08:34:55 - l_default - DEBUG - Free memory in bytes: 0.0
2017/12/04 08:34:55 - l_default - ERROR - Free gpu mem is 0.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/04 08:34:55 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:34:55 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:34:55 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:34:55 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:34:55 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable
2017/12/04 08:35:20 - l_default - DEBUG - Current time detected is 1512372920.5 runtime calculated is 1009
2017/12/04 08:35:20 - l_default - DEBUG - Free gpu memory value is 405M
2017/12/04 08:35:20 - l_default - DEBUG - Free memory in bytes: 424673280.0
2017/12/04 08:35:20 - l_default - DEBUG - 192.168.7.55 : 1051 Connectable
2017/12/04 08:35:20 - l_default - DEBUG - 192.168.7.59 : 1091 Connectable
2017/12/04 08:35:20 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/04 08:35:20 - l_default - DEBUG - 192.168.7.57 : 1071 Connectable
2017/12/04 08:35:20 - l_default - DEBUG - 192.168.7.52 : 1021 Connectable

**Comment by SvenVD** [comment]
Try running with one camera feed, is this also giving a delay?

**Comment by skowron0** [comment]
Log when I connect one cam:
2017/12/07 07:36:20 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:36:46 - l_default - DEBUG - stats_counter is 19. Only sending every 40
2017/12/07 07:36:46 - l_default - DEBUG - Free gpu memory value is 0
2017/12/07 07:36:46 - l_default - DEBUG - Free memory in bytes: 0.0
2017/12/07 07:36:46 - l_default - ERROR - Free gpu mem is 0.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/07 07:36:46 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:37:11 - l_default - DEBUG - stats_counter is 20. Only sending every 40
2017/12/07 07:37:11 - l_default - DEBUG - Free gpu memory value is 493M
2017/12/07 07:37:11 - l_default - DEBUG - Free memory in bytes: 516947968.0
2017/12/07 07:37:11 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:37:36 - l_default - DEBUG - stats_counter is 21. Only sending every 40
2017/12/07 07:37:36 - l_default - DEBUG - Free gpu memory value is 288
2017/12/07 07:37:36 - l_default - DEBUG - Free memory in bytes: 288.0
2017/12/07 07:37:36 - l_default - ERROR - Free gpu mem is 288.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/07 07:37:36 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:38:01 - l_default - DEBUG - stats_counter is 22. Only sending every 40
2017/12/07 07:38:01 - l_default - DEBUG - Free gpu memory value is 493M
2017/12/07 07:38:01 - l_default - DEBUG - Free memory in bytes: 516947968.0
2017/12/07 07:38:01 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:38:26 - l_default - DEBUG - stats_counter is 23. Only sending every 40
2017/12/07 07:38:26 - l_default - DEBUG - Free gpu memory value is 9K
2017/12/07 07:38:26 - l_default - DEBUG - Free memory in bytes: 9216.0
2017/12/07 07:38:26 - l_default - ERROR - Free gpu mem is 9216.0 bytes which is less than 80000000 bytes. Streams might fail to start. Consider assigning more memory to gpu in /boot/config.txt with the gpu_mem option
2017/12/07 07:38:26 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable
2017/12/07 07:38:51 - l_default - DEBUG - stats_counter is 24. Only sending every 40
2017/12/07 07:38:51 - l_default - DEBUG - Free gpu memory value is 493M
2017/12/07 07:38:51 - l_default - DEBUG - Free memory in bytes: 516947968.0
2017/12/07 07:38:51 - l_default - DEBUG - 192.168.7.58 : 1081 Connectable

**Comment by skowron0** [comment]
There is also a delay on one camera.

**Comment by skowron0** [comment]
Hi,

When I set: memory_usage_check: False, the problems with the delay have gone away. I'm testing the second day and everything is ok.

**Comment by SvenVD** [comment]
Thanks for your debugging can anybody else who have the same delays confirm the solution by setting memory_usage_check False?

Thanks

**Comment by dhsemp** [comment]
It didn’t work for me.  I’m using UniFi Protect (UCK-G2+) into a fully updated Rpi3 running rpisurv.  After 12-24hrs, the video will be delayed by minutes.  UBNT says it’s a problem with omxplayer even though it works fine with their legacy NVR running UniFi Video 3.

Any idea what additional omxplayer or rpisurv debug settings I can enable to figure out exactly what’s causing the delay issues?  Could it really be buffering on the Rpi3?

**Comment by syadnom** [comment]
@dhsemp protect still has some serious rtsp bugs.  Try playing a stream via vlc and you'll see the same behavior.

**Comment by syadnom** [comment]
@dhsemp  omxplayer does have some peculiarities, but that's not the problem here.  Protect is doing some weird things in it's RTSP implementation and ubnt knows it.  

As of right now, you cannot get a reliable RTSP stream out of protect using any known software on any platform.

I have 8 protect/ck2+ systems and they all have the exact some very predictable issues with RTSP streams.

**Comment by SvenVD** [comment]
Would it just be the worker.py file I'd have to modify?--> yes. Please report back if that fixed your issue, and if ubiquity fixed their problem.
