### ISSUE TITLE
Looking for way to add mix of h264 and mjpeg cameras 

### ISSUE THREAD

**Issue by dannyzumwalt** [SvenVD/rpisurv#49]
Using omxplayer on raspbian, i can get mjpeg streams to play from command line with a http cgi address: 

http://192.168.1.45:2080/videostream.cgi

Is there a way to add this to /etc/ripsurv config to add it to my existing (currently 3) h264 streams? When i enter rtsp_url: "http://192.168.1.45:2080/videostream.cgi" rpisurv starts, but the mjpeg stream never starts. 

2018/01/16 20:10:44 - l_default - ERROR - 192.168.1.45 : 2080 Not Connectable (failed socket connect)

Obviously it's trying to use RTSP protocol instead of http. How to override?

**Comment by SvenVD** [comment]
This is currently not supported. I am open to a  pull request for this.

**Comment by dannyzumwalt** [comment]
Not familiar with git too much or pull requests.

**Comment by SvenVD** [comment]
This has now been implemented, currently still beta, check https://github.com/SvenVD/rpisurv/blob/v2.0_branch/RELEASE_NOTES.md
