### ISSUE TITLE
Kenik Cam can't connect via RSTP

### ISSUE THREAD

**Issue by blackangelPL** [SvenVD/rpisurv#53]
`Mar 19 13:44:06 raspberrypi systemd[1]: rpisurv.service start request repeated too quickly, refusing to start.
Mar 19 13:44:06 raspberrypi systemd[1]: Failed to start Rpisurv Raspberry Pi Surveillance.
Mar 19 13:44:06 raspberrypi systemd[1]: Unit rpisurv.service entered failed state.
pi@raspberrypi:~/rpisurv $ mc
GNU nano 2.2.6 File: /var/log/syslog Modified

Mar 19 14:31:03 raspberrypi rpisurv[4147]: while not self.check_event(MappingEndEvent):
Mar 19 14:31:03 raspberrypi rpisurv[4147]: File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
Mar 19 14:31:03 raspberrypi rpisurv[4147]: self.current_event = self.state()
Mar 19 14:31:03 raspberrypi rpisurv[4147]: File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
Mar 19 14:31:03 raspberrypi rpisurv[4147]: "expected , but found %r" % token.id, token.start_mark)
Mar 19 14:31:03 raspberrypi rpisurv[4147]: yaml.parser.ParserError: while parsing a block mapping
Mar 19 14:31:03 raspberrypi rpisurv[4147]: in "conf/surveillance.yml", line 1, column 1
Mar 19 14:31:03 raspberrypi rpisurv[4147]: expected , but found '-'
Mar 19 14:31:03 raspberrypi rpisurv[4147]: in "conf/surveillance.yml", line 14, column 1
Mar 19 14:31:03 raspberrypi systemd[1]: rpisurv.service: main process exited, code=exited, status=1/FAILURE
Mar 19 14:31:03 raspberrypi systemd[1]: Unit rpisurv.service entered failed state.
Mar 19 14:31:04 raspberrypi systemd[1]: rpisurv.service holdoff time over, scheduling restart.
Mar 19 14:31:04 raspberrypi systemd[1]: Stopping Rpisurv Raspberry Pi Surveillance...
Mar 19 14:31:04 raspberrypi systemd[1]: Starting Rpisurv Raspberry Pi Surveillance...
Mar 19 14:31:04 raspberrypi systemd[1]: rpisurv.service start request repeated too quickly, refusing to start.
Mar 19 14:31:04 raspberrypi systemd[1]: Failed to start Rpisurv Raspberry Pi Surveillance.
Mar 19 14:31:04 raspberrypi systemd[1]: Unit rpisurv.service entered failed state.
Mar 19 14:31:08 raspberrypi vncserver-x11[658]: AgentInitCheck: no response from agent
if i use omxplayer
omxplayer --live --win "0 100 1824 642" rtsp://10.20.2.210/user=admin_password=_channel=0_stream=1.sdp
it works

When i put the same adres to rpirurv it wont start

**Comment by SvenVD** [comment]
There is a problem with your yaml format according to your logs. Please make sure all the indents are the OK. Do not use tabs. Example see here https://github.com/SvenVD/rpisurv/blob/master/surveillance/conf/surveillance.yml. Put a space behind - also

**Comment by SvenVD** [comment]
Any update?
