### ISSUE TITLE
Request: Date and Time

### ISSUE THREAD

**Issue by noticz** [SvenVD/rpisurv#58]
First of all, just wanted to say thanks for coming up with this RPISURV, it's great!

I looked a little bit to try and see if this was even possible for a date and time display and wasn't successful but how difficult would this project be to add a date and time along the bottom?

I have two reasons for the date and time usage:
1. To be able to look up and see the date and time with seconds.
2. We have had the Pi freeze up about 10 times or so but we don't even realize it has frozen until our motion alert goes off on the screen. I setup the watchdog so I hope the freezing issue is fixed with the watchdog.  As far as motion alert I just have our camera server send a ssh motion alert sound to the rpi on alert.

**Comment by SvenVD** [comment]
Hi, you can easily achieve this by letting your videostreams include the date and time, that's how I do it.

Currently no plans for a date time overlay, but I will add  to the backlog
