### ISSUE TITLE
req: extend rpisurv to use mplayer/other

### ISSUE THREAD

**Issue by syadnom** [SvenVD/rpisurv#59]
I use a ton of raspberry pi's for video playback, but I'd like to occasionally use more powerful hardware without changing underlying software.

For example, an Intel NUC6CAYH supports 4k output and should be able to decode a 4x4 grid of h.264 streams with mplayer using -vo vaapi or ffmpeg using vaapi or opencl.

This would be an incredibly useful modification.

I would be willing to fork out some cash to make this happen, and I'm assuming a few others would pitch in because of how great this would be.  I can only get a 3x3 grid of 640x360 streams at 1080p output decoding on a pi3 before it runs out of power.  I'm also stuck at an effect 1080p output with the Pi3.  I can technically push out 4k15fps which would be fine but I can't decode enough streams to make use of that.

Ultimately I want to stick with rpisurv but have a higher end device that can decode 16x 640x360 stream or maybe even 16x 1024x576 streams, and sometimes just 4x 1080p streams.  Those are by resolution options from the Unifi-video cameras I use most of and the occasional axis camera resolutions are pretty close.

**Comment by SvenVD** [comment]
Hi, I thinks this is a great idea. However currently I do not have the spare time to invest in this feature. I am open to pull requests. Anyhow when I have some time I will start implementing feature requests, which gets implemented first depends on popularity and what we think would fit best in the current rpisurv future view.

**Comment by SvenVD** [comment]
I created a feature request list on https://feathub.com/SvenVD/rpisurv
