### ISSUE TITLE
Screen Sizes

### ISSUE THREAD

**Issue by klarlichter** [SvenVD/rpisurv#65]
Hello,
did you also implement function to add for each camera different sizes? That it is not like 2x2 that it can be also such like
1 row: 2 cams
2 row 1 cam and so on?

**Comment by SvenVD** [comment]
Currently all streams will be displayed in same size. I suppose what you are requesting is more like this feature request: https://feathub.com/SvenVD/rpisurv/+11 ?

**Comment by klarlichter** [comment]
Yes. Right. I hope that will be possible.

—
Mit freundlichen Grüßen
S.Linge



On Sat, Aug 25, 2018 at 5:38 PM +0200, "SvenVD" <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently all streams will be displayed in same size. I suppose what you are requesting is more like this feature request: https://feathub.com/SvenVD/rpisurv/+11 ?
