### ISSUE TITLE
cannot clone

### ISSUE THREAD

**Issue by pal251** [SvenVD/rpisurv#7]
When I go through the instructions and get to this part , this happens

sudo git clone git@github.com:SvenVD/rpisurv.git
Cloning into 'rpisurv'...
The authenticity of host 'github.com (192.30.252.121)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.121' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any idea of what I am doing wrong?  New to Pi and Linux

**Comment by SvenVD** [comment]
I changed the readme. 

Please use `https://github.com/SvenVD/rpisurv` this is less error prone
