### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by stormdog10** [SvenVD/rpisurv#75]
Hi Rpisurv fails to start i get the following error 

sudo systemctl status rpisurv
● rpisurv.service - Rpisurv Raspberry Pi Surveillance
   Loaded: loaded (/etc/systemd/system/rpisurv.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-10-21 13
  Process: 26436 ExecStart=/usr/bin/rpisurv (code=exited, status=1/FAILURE)
 Main PID: 26436 (code=exited, status=1/FAILURE)

Oct 21 13:49:56 raspberrypi systemd[1]: rpisurv.service: Failed with result 'exi
...skipping...
● rpisurv.service - Rpisurv Raspberry Pi Surveillance
   Loaded: loaded (/etc/systemd/system/rpisurv.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-10-21 13
  Process: 26436 ExecStart=/usr/bin/rpisurv (code=exited, status=1/FAILURE)
 Main PID: 26436 (code=exited, status=1/FAILURE)

Oct 21 13:49:56 raspberrypi systemd[1]: rpisurv.service: Failed with result 'exi
~

This even running it with your example script!I have also checked it in yami and it passes. i only need to pull one rtsp stream just now

**Comment by SvenVD** [comment]
Hi
What version are you using?  the example file of version 2.0 explicitly states:

#THE FOLLOWING ARE EXAMPLES WITH ALL OPTIONS EXPLAINED, REMOVE OR ADAPT THEM WITH YOUR REAL CONFIG

The example config file is a "documentation" example and can not be used to start rpisurv without changes. You need to replace the examples with your config.

Can you show me the log of rpisurv in /var/log/daemon.log and the main.log in /usr/local/bin/rpisurv/logs/

Thanks
