### ISSUE TITLE
RPISurv with UniFi camera's / connecting message

### ISSUE THREAD

**Issue by Quarco** [SvenVD/rpisurv#89]
Setup:
Couple of UniFi camera's with NVR. RPISurv connects to streams delivered by this NVR.

Problem:
When rpisurv can't connect to a stream (@startup) the notice 'connecting to stream' does not go away.
systemctl restart rpisurv.service makes all streams visible on screen.

My research:
When configured for 4 streams omxplayer.bin is started 4 times. This number doesn't change / no new instances are started, etc.. (ps aux on cli)
The rtsp-URL is connectable (when copy pasted in VLC i see the video)
I have multiple RPI's and problem is on all devices. No hardware / network issue.

Please help, software is superb :-)
Kind regards,
Marco Snoek

**Comment by SvenVD** [comment]
Hi, support questions go here:
https://community.rpisurv.net/
Github is only for bugs

To speed up troubleshooting please add the following to your question/topic:

    Enable debug logging by opening a terminal and pasting following command:

    Code: Select all

     sed -i 's/level:.*/level: DEBUG/g' /usr/local/bin/rpisurv/conf/logging.yml; systemctl restart rpisurv

    Paste the most recent logs of /var/log/daemon.log and /usr/local/bin/rpisurv/logs/main.log, if possible enable debug logging first
    Lookup the version you are running

**Comment by SvenVD-be** [comment]
Any update?
