### ISSUE TITLE
request:  placeholders be animated gifs or videos

### ISSUE THREAD

**Issue by syadnom** [SvenVD/rpisurv#91]
I'd like the placeholder videos to have motion.  Like a modern wait circle or something like that.  Would need to have some sort of animated image format or video.

**Comment by SvenVD** [comment]
Hi thanks for your request.

Note that github tickets are only for potential bug solving, https://community.rpisurv.net/ is right place for your requests

I added your request here: https://www.tapatalk.com/groups/rpisurv/show-random-images-from-an-accessible-url-instead--t6.html
