### ISSUE TITLE
Draw videos over desktop

### ISSUE THREAD

**Issue by Anonym-tsk** [SvenVD/rpisurv#93]
I'm looking for stable omxplayer wrapper to draw video from camera over my interface.
I use MagicMirror and i want to draw video over MagicMirror interface.
Is it possible to set coordinates and size for rpisurv?

**Comment by SvenVD** [comment]
rpisurv/omxplayer claims all the pixels. So everything from magicmirror will be hidden, rpisurv autocalculates the positions but you can override to some extend on pixel base.

https://community.rpisurv.net is the right place to ask questions

Thanks

**Comment by Anonym-tsk** [comment]
@SvenVD could you make this feature in next releases?

**Comment by SvenVD** [comment]
Feature requests are handled here: https://community.rpisurv.net. What exactly is it you want.
