### ISSUE TITLE
service does not start  on RPI3 B+

### ISSUE THREAD

**Issue by fellowgeek** [SvenVD/rpisurv#94]
## service does not start  on RPI3 B+

root@raspberrypi:/etc# service rpisurv status
● rpisurv.service - Rpisurv Raspberry Pi Surveillance
   Loaded: loaded (/etc/systemd/system/rpisurv.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-09-09 03:23:54 BST; 2s ago
  Process: 819 ExecStart=/usr/bin/rpisurv (code=exited, status=1/FAILURE)
 Main PID: 819 (code=exited, status=1/FAILURE)

Sep 09 03:23:54 raspberrypi systemd[1]: rpisurv.service: Failed with result 'exit-code'.

**Comment by SvenVD** [comment]
Support questions are handled here: https://community.rpisurv.net. 
Please provide the [logs](https://www.tapatalk.com/groups/rpisurv/guidelines-t13.html) to assist you further.
