### ISSUE TITLE
Specifying nr_of_columns per screen keeps the service from starting

### ISSUE THREAD

**Issue by coolrunnings82** [SvenVD/rpisurv#95]
If I put anything in nr_of_columns other than the default value, and that line is only there once, everything works fine. If I specify it per camera group, the service fails to start.

**Comment by SvenVD** [comment]
Hi, most likely you made an error in your config file.

To support you further we need some additional information:

Support questions are handled here: https://community.rpisurv.net. 
Please provide the [logs](https://www.tapatalk.com/groups/rpisurv/guidelines-t13.html) to assist you further.
