### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by BigHomie90** [SvenVD/rpisurv#97]
Hello..I messed up the installation and now my screen flickers every 2-3 seconds. How do I remove the installation?

**Comment by SvenVD** [comment]
(Normally support questions are handled here: https://community.rpisurv.net.)

The following commands disable and stop rpisurv.
`systemctl stop rpisurv;
systemctl disable rpisurv
`
If the screen still flickers then probably there was a setting that was set outside of rpisurv installer.

**Comment by BigHomie90** [comment]
Alright, everything's fine now. Thank you very much for your immediate reply and sorry for posting in the wrong place.
