### ISSUE TITLE
Does the system work on RPi4 and 4k displays?

### ISSUE THREAD

**Issue by shark92651** [SvenVD/rpisurv#98]
I have used the displaycameras software in the past on an RPi3 and Raspbian buster for a single camera feed and it worked fine. Now I have purchased an RPi4 4GB and a 4K TV and attempting to display a 9 camera 3x3 matrix of feeds at 704x480. I initially wanted to display 16 cameras in a 4x4 matrix but was told that omxplayer will not support more than 15 feeds. So far I cannot get more than 7 feeds on a 4k30hz monitor mode, and only 5 will display on a 4k60hz mode. In order to get these feeds to work I have to set gpu_mem > 512 (which the docs state is "untested" ) otherwise I get severe flashing between the different feeds. 

I was considering switching to rpisurv but I fear my underlying issues are with the Rasbpian support for 4k monitors or in omxplayer itself. Has anyone been able to successfully display 9 or more cameras with an RPi4 and a 4k display or are there known issues? I appreciate any input.

**Comment by SvenVD** [comment]
(Normally support questions are handled here: https://community.rpisurv.net.) This is for bugs only.

You could better ask your question there. https://www.tapatalk.com/groups/rpisurv/raspberry-pi-4-t32-s40.html
