### ISSUE TITLE
Feature Request: API Interface

### ISSUE THREAD

**Issue by dlasher** [SvenVD/rpisurv#99]
Love the project, thank you, works well.

It would be nice to be able to check status, remote control "screen" switching, etc from either a telnet-type interface, or via an API/post/REST/etc.

Primary Application: When XX action occurs, switch rpisurv to F1/F2/F3/F4/etc camera stream. This would allow integration with home automation and/or security triggers like doors, motion, etc.

Secondary Application : pulling stats via API, (zabbix maybe?)

**Comment by SvenVD** [comment]
Hi feature requests are tracked here: https://www.tapatalk.com/groups/rpisurv/feature-requests-f7/

Im always open for a pull request that adds an API
